# Generated by Django 4.0.2 on 2022-02-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffer',
            name='photo',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/'),
        ),
    ]
