# Generated by Django 4.0.2 on 2022-02-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combine', '0002_alter_buffer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.DeleteModel(
            name='Buffer',
        ),
    ]
